### ISSUE TITLE
Birdie crashing at start

### ISSUE THREAD

**Issue by germanocorrea** [needle-and-thread/birdie#193] opened 2016-12-29 17:56 UTC
Birdie is crashing and closing at start. It happened once when I first opened, without logging in my Twitter account. Opening again I was able to log in, and use a bit the app, but when I was going to write a tweet, it crashed. Now, it crashes almost all the time when I open it. Four times consecutively, but in the fifth I tried to resize the window before it finishes the loading, and it didn't crashed.

As the log generated while opening from terminal is different from other issues I've seen here, I am sending them again.

Running Elementary OS 0.4 Loki (64-bit), Birdie installed via ppa `ppa:birdie-team/daily`.

```
λ ggcorrea [~/Downloads] → birdie
*** Error in `birdie': realloc(): invalid pointer: 0x00007efc5c182d00 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7efc5982f7e5]
/lib/x86_64-linux-gnu/libc.so.6(realloc+0x348)[0x7efc5983be58]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_realloc+0x28)[0x7efc59f0a7e8]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x16d209)[0x7efc5b9c7209]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x16d43a)[0x7efc5b9c743a]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x16c22d)[0x7efc5b9c622d]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(+0x206bb1)[0x7efc5ba60bb1]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_type_create_instance+0x1f9)[0x7efc5a1ff359]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(+0x1531b)[0x7efc5a1e131b]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_newv+0xd1)[0x7efc5a1e2c01]
/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0(g_object_new+0x104)[0x7efc5a1e3534]
/usr/lib/x86_64-linux-gnu/libgtk-3.so.0(gtk_list_box_insert+0x21d)[0x7efc5ba6475d]
birdie[0x45f2d0]
birdie[0x45f356]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x15a)[0x7efc59f0505a]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4a400)[0x7efc59f05400]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7efc59f054ac]
/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0(g_application_run+0x20d)[0x7efc5a4cccdd]
/usr/lib/x86_64-linux-gnu/libgranite.so.3(granite_application_run+0x1a0)[0x7efc5f12cf30]
birdie(birdie_main+0x76)[0x4126fc]
birdie(main+0x20)[0x412745]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7efc597d8830]
birdie(_start+0x29)[0x4125b9]
======= Memory map: ========
00400000-004b4000 r-xp 00000000 08:02 5767315                            /usr/bin/birdie
006b4000-006b5000 r--p 000b4000 08:02 5767315                            /usr/bin/birdie
006b5000-006b7000 rw-p 000b5000 08:02 5767315                            /usr/bin/birdie
02338000-03b99000 rw-p 00000000 00:00 0                                  [heap]
7efc28000000-7efc2821e000 rw-p 00000000 00:00 0 
7efc2821e000-7efc2c000000 ---p 00000000 00:00 0 
7efc2c000000-7efc2c021000 rw-p 00000000 00:00 0 
7efc2c021000-7efc30000000 ---p 00000000 00:00 0 
7efc30000000-7efc3002c000 rw-p 00000000 00:00 0 
7efc3002c000-7efc34000000 ---p 00000000 00:00 0 
7efc34623000-7efc34906000 r--p 00000000 08:02 45271                      /usr/share/fonts/truetype/ancient-scripts/Symbola_hint.ttf
7efc34906000-7efc3493d000 r--p 00000000 08:02 45532                      /usr/share/fonts/truetype/open-sans-elementary/OpenSans-Bold.ttf
7efc34a8f000-7efc34a94000 r-xp 00000000 08:02 13284                      /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so
7efc34a94000-7efc34c93000 ---p 00005000 08:02 13284                      /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so
7efc34c93000-7efc34c94000 r--p 00004000 08:02 13284                      /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so
7efc34c94000-7efc34c95000 rw-p 00005000 08:02 13284                      /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-jpeg.so
7efc34c95000-7efc34c96000 ---p 00000000 00:00 0 
7efc34c96000-7efc35496000 rw-p 00000000 00:00 0 
7efc35496000-7efc3549b000 r-xp 00000000 08:02 135554                     /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7efc3549b000-7efc3569b000 ---p 00005000 08:02 135554                     /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7efc3569b000-7efc3569c000 r--p 00005000 08:02 135554                     /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7efc3569c000-7efc3569d000 rw-p 00006000 08:02 135554                     /lib/x86_64-linux-gnu/libnss_dns-2.23.so
7efc3569d000-7efc3569f000 r-xp 00000000 08:02 135642                     /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7efc3569f000-7efc3589e000 ---p 00002000 08:02 135642                     /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7efc3589e000-7efc3589f000 r--p 00001000 08:02 135642                     /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7efc3589f000-7efc358a0000 rw-p 00002000 08:02 135642                     /lib/x86_64-linux-gnu/libnss_mdns4_minimal.so.2
7efc358a0000-7efc358ab000 r-xp 00000000 08:02 135555                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
7efc358ab000-7efc35aaa000 ---p 0000b000 08:02 135555                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
7efc35aaa000-7efc35aab000 r--p 0000a000 08:02 135555                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
7efc35aab000-7efc35aac000 rw-p 0000b000 08:02 135555                     /lib/x86_64-linux-gnu/libnss_files-2.23.so
7efc35aac000-7efc35ab2000 rw-p 00000000 00:00 0 
7efc35ab2000-7efc35ab3000 ---p 00000000 00:00 0 
7efc35ab3000-7efc362b3000 rw-p 00000000 00:00 0 
7efc362b3000-7efc362b8000 r-xp 00000000 08:02 13282                      /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
7efc362b8000-7efc364b7000 ---p 00005000 08:02 13282                      /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
7efc364b7000-7efc364b8000 r--p 00004000 08:02 13282                      /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
7efc364b8000-7efc364b9000 rw-p 00005000 08:02 13282                      /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-png.so
7efc364b9000-7efc364f0000 r--p 00000000 08:02 45537                      /usr/share/fonts/truetype/open-sans-elementary/OpenSans-Light.ttf
7efc364f0000-7efc36570000 rw-s 00000000 00:05 10059788                   /SYSV00000000 (deleted)
7efc36570000-7efc36574000 r-xp 00000000 08:02 14849                      /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
7efc36574000-7efc36773000 ---p 00004000 08:02 14849                      /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
7efc36773000-7efc36774000 r--p 00003000 08:02 14849                      /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
7efc36774000-7efc36775000 rw-p 00004000 08:02 14849                      /usr/lib/x86_64-linux-gnu/gio/modules/libgiognomeproxy.so
7efc36775000-7efc367f4000 r-xp 00000000 08:02 8529                       /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7efc367f4000-7efc369f3000 ---p 0007f000 08:02 8529                       /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7efc369f3000-7efc369f4000 r--p 0007e000 08:02 8529                       /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7efc369f4000-7efc369f5000 rw-p 0007f000 08:02 8529                       /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7efc369f5000-7efc36a27000 r-xp 00000000 08:02 8657                       /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7efc36a27000-7efc36c26000 ---p 00032000 08:02 8657                       /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7efc36c26000-7efc36c27000 r--p 00031000 08:02 8657                       /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7efc36c27000-7efc36c28000 rw-p 00032000 08:02 8657                       /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7efc36c28000-7efc36c5c000 r-xp 00000000 08:02 8854                       /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7efc36c5c000-7efc36e5b000 ---p 00034000 08:02 8854                       /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7efc36e5b000-7efc36e5d000 r--p 00033000 08:02 8854                       /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7efc36e5d000-7efc36e5e000 rw-p 00035000 08:02 8854                       /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7efc36e5e000-7efc36e6f000 r-xp 00000000 08:02 9138                       /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7efc36e6f000-7efc3706f000 ---p 00011000 08:02 9138                       /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7efc3706f000-7efc37070000 r--p 00011000 08:02 9138                       /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7efc37070000-7efc37071000 rw-p 00012000 08:02 9138                       /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7efc37071000-7efc37194000 r-xp 00000000 08:02 8547                       /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7efc37194000-7efc37393000 ---p 00123000 08:02 8547                       /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7efc37393000-7efc3739e000 r--p 00122000 08:02 8547                       /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7efc3739e000-7efc373a0000 rw-p 0012d000 08:02 8547                       /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7efc373a0000-7efc373a1000 rw-p 00000000 00:00 0 
7efc373a1000-7efc373fa000 r-xp 00000000 08:02 8919                       /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7efc373fa000-7efc375f9000 ---p 00059000 08:02 8919                       /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7efc375f9000-7efc37603000 r--p 00058000 08:02 8919                       /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7efc37603000-7efc37605000 rw-p 00062000 08:02 8919                       /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7efc37624000-7efc3763f000 r-xp 00000000 08:02 14850                      /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
7efc3763f000-7efc3783e000 ---p 0001b000 08:02 14850                      /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
7efc3783e000-7efc3783f000 r--p 0001a000 08:02 14850                      /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
7efc3783f000-7efc37840000 rw-p 0001b000 08:02 14850                      /usr/lib/x86_64-linux-gnu/gio/modules/libgiognutls.so
7efc37840000-7efc3788c000 r--p 00000000 08:02 45283                      /usr/share/fonts/truetype/croscore/Cousine-Regular.ttf
7efc3788c000-7efc378c3000 r-xp 00000000 08:02 8278                       /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3.0.1
7efc378c3000-7efc37ac3000 ---p 00037000 08:02 8278                       /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3.0.1
7efc37ac3000-7efc37ac6000 r--p 00037000 08:02 8278                       /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3.0.1
7efc37ac6000-7efc37ac7000 rw-p 0003a000 08:02 8278                       /usr/lib/x86_64-linux-gnu/libcroco-0.6.so.3.0.1
7efc37ac7000-7efc37afc000 r-xp 00000000 08:02 9037                       /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.40.13
7efc37afc000-7efc37cfc000 ---p 00035000 08:02 9037                       /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.40.13
7efc37cfc000-7efc37cfd000 r--p 00035000 08:02 9037                       /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.40.13
7efc37cfd000-7efc37cfe000 rw-p 00036000 08:02 9037                       /usr/lib/x86_64-linux-gnu/librsvg-2.so.2.40.13
7efc37d18000-7efc37d19000 rw-p 00000000 00:00 0 
7efc37d19000-7efc37d1b000 r--p 00000000 08:02 5768633                    /usr/share/locale/pt/LC_MESSAGES/birdie.mo
7efc37d1b000-7efc37d1d000 r--p 00000000 08:02 5768630                    /usr/share/locale/pt_BR/LC_MESSAGES/birdie.mo
7efc37d1d000-7efc37d1f000 r-xp 00000000 08:02 14841                      /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7efc37d1f000-7efc37f1e000 ---p 00002000 08:02 14841                      /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7efc37f1e000-7efc37f1f000 r--p 00001000 08:02 14841                      /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7efc37f1f000-7efc37f20000 rw-p 00002000 08:02 14841                      /usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders/libpixbufloader-svg.so
7efc37f20000-7efc37f26000 r--p 00000000 08:02 5767330                    /usr/share/icons/hicolor/icon-theme.cache
7efc37f26000-7efc37f42000 r--p 00000000 08:02 72192                      /usr/share/icons/gnome/icon-theme.cache
7efc37f42000-7efc37f4b000 r--p 00000000 08:02 72817                      /usr/share/icons/Adwaita/icon-theme.cache
7efc37f4b000-7efc37f61000 r--p 00000000 08:02 19641                      /usr/share/icons/elementary/icon-theme.cache
7efc37f61000-7efc37f97000 r--p 00000000 08:02 45539                      /usr/share/fonts/truetype/open-sans-elementary/OpenSans-Regular.ttf
7efc37f97000-7efc37f9e000 r--s 00000000 08:02 11284611                   /var/cache/fontconfig/4be9850f182b35c1350b6bbf2e42601c-le64.cache-6
7efc37f9e000-7efc37fa9000 r--s 00000000 08:02 11281709                   /var/cache/fontconfig/945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-6
7efc37fa9000-7efc37fab000 r--s 00000000 08:02 11287411                   /var/cache/fontconfig/99e8ed0e538f840c565b6ed5dad60d56-le64.cache-6
7efc37fab000-7efc37fc0000 r--s 00000000 08:02 11285417                   /var/cache/fontconfig/04aabc0a78ac019cf9454389977116d2-le64.cache-6
7efc37fc0000-7efc38000000 r--s 00000000 08:02 11285403                   /var/cache/fontconfig/0bd3dc0958fa2205aaaa8ebb13e2872b-le64.cache-6
7efc38000000-7efc38022000 rw-p 00000000 00:00 0 
7efc38022000-7efc3c000000 ---p 00000000 00:00 0 
7efc3c000000-7efc3c022000 rw-p 00000000 00:00 0 
7efc3c022000-7efc40000000 ---p 00000000 00:00 0 
7efc40000000-7efc40021000 rw-p 00000000 00:00 0 
7efc40021000-7efc44000000 ---p 00000000 00:00 0 
7efc44000000-7efc44001000 r--p 00000000 08:02 119998                     /usr/share/locale-langpack/pt_BR/LC_MESSAGES/glib-networking.mo
7efc44001000-7efc4400a000 r--s 00000000 08:02 11285420                   /var/cache/fontconfig/a6d8cf8e4ec09cdbc8633c31745a07dd-le64.cache-6
7efc4400a000-7efc44010000 r--s 00000000 08:02 11285419                   /var/cache/fontconfig/2cd17615ca594fa2959ae173292e504c-le64.cache-6
7efc44010000-7efc44011000 r--s 00000000 08:02 11285418                   /var/cache/fontconfig/0d8c3b2ac0904cb8a57a757ad11a4a08-le64.cache-6
7efc44011000-7efc44012000 r--s 00000000 08:02 11285416                   /var/cache/fontconfig/1ac9eb803944fde146138c791f5cc56a-le64.cache-6
7efc44012000-7efc44017000 r--s 00000000 08:02 11285415                   /var/cache/fontconfig/eb48934c523a49add3824bfad8846c40-le64.cache-6
7efc44017000-7efc4401c000 r--s 00000000 08:02 11285414                   /var/cache/fontconfig/385c0604a188198f04d133e54aba7fe7-le64.cache-6
7efc4401c000-7efc4401d000 r--s 00000000 08:02 11285413                   /var/cache/fontconfig/dc05db6664285cc2f12bf69c139ae4c3-le64.cache-6
7efc4401d000-7efc44021000 r--s 00000000 08:02 11285412                   /var/cache/fontconfig/f0b0891f3a988e97b2aa7c076a1430f3-le64.cache-6
7efc44021000-7efc44023000 r--s 00000000 08:02 11285410                   /var/cache/fontconfig/6adb16404e170b9523f41c0701dd4690-le64.cache-6
7efc44023000-7efc44027000 r--s 00000000 08:02 11285409                   /var/cache/fontconfig/7b79abe4499501fcd4e4826394083a53-le64.cache-6
7efc44027000-7efc4402a000 r--s 00000000 08:02 11285408                   /var/cache/fontconfig/3a9914ff62a69b32234685a84fdc926d-le64.cache-6
7efc4402a000-7efc4402d000 r--s 00000000 08:02 11285407                   /var/cache/fontconfig/767a8244fc0220cfb567a839d0392e0b-le64.cache-6
7efc4402d000-7efc4402e000 r--s 00000000 08:02 11285406                   /var/cache/fontconfig/0b41ebd278d9388cf5d83f81d476c672-le64.cache-6
7efc4402e000-7efc4402f000 r--s 00000000 08:02 11272304                   /var/cache/fontconfig/4794a0821666d79190d59a36cb4f44b5-le64.cache-6
7efc4402f000-7efc44033000 r--s 00000000 08:02 11285404                   /var/cache/fontconfig/ea32c683f96734b73b6a7acf745d6442-le64.cache-6
7efc44033000-7efc44039000 r--s 00000000 08:02 11285402                   /var/cache/fontconfig/8801497958630a81b71ace7c5f9b32a8-le64.cache-6
7efc44039000-7efc4403a000 r--s 00000000 08:02 11285401                   /var/cache/fontconfig/bab58bb527bb656aaa9f116d68a48d89-le64.cache-6
7efc4403a000-7efc4403b000 r--s 00000000 08:02 11285400                   /var/cache/fontconfig/b036df7bbb72844893df6bcf5570ea7f-le64.cache-6
7efc4403b000-7efc4403c000 r--s 00000000 08:02 11285399                   /var/cache/fontconfig/575107dd7452b4b2b2b1361909925bb4-le64.cache-6
7efc4403c000-7efc44043000 r--s 00000000 08:02 11285398                   /var/cache/fontconfig/3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-6
7efc44043000-7efc44044000 r--s 00000000 08:02 11285397                   /var/cache/fontconfig/56cf4f4769d0f4abc89a4895d7bd3ae1-le64.cache-6
7efc44044000-7efc44045000 r--s 00000000 08:02 11285396                   /var/cache/fontconfig/b9d506c9ac06c20b433354fa67a72993-le64.cache-6
7efc44045000-7efc4404b000 r--s 00000000 08:02 11285395                   /var/cache/fontconfig/b47c4e1ecd0709278f4910c18777a504-le64.cache-6
7efc4404b000-7efc4404c000 r--s 00000000 08:02 11285394                   /var/cache/fontconfig/0b3f2427388044a01a5738fa4b8cc9d1-le64.cache-6
7efc4404c000-7efc4404d000 r--s 00000000 08:02 11285393                   /var/cache/fontconfig/0941b6d3777f1e64883d36fd6d84a52f-le64.cache-6
7efc4404d000-7efc44055000 r--s 00000000 08:02 11287409                   /var/cache/fontconfig/52f7bdb7ce746bfd7eaa1985bd9cfa93-le64.cache-6
7efc44055000-7efc44058000 r--s 00000000 08:02 11272300                   /var/cache/fontconfig/e49e89034d371f0f9de17aab02136486-le64.cache-6
7efc44058000-7efc4405a000 r--s 00000000 08:02 11272299                   /var/cache/fontconfig/4b14b093aebc79c320de5e86ae1d3314-le64.cache-6
7efc4405a000-7efc4406d000 r--s 00000000 08:02 11285390                   /var/cache/fontconfig/d52a8644073d54c13679302ca1180695-le64.cache-6
7efc4406d000-7efc4406e000 r--s 00000000 08:02 11285389                   /var/cache/fontconfig/551ecf3b0e8b0bca0f25c0944f561853-le64.cache-6
7efc4406e000-7efc44079000 r--s 00000000 08:02 11285388                   /var/cache/fontconfig/d589a48862398ed80a3d6066f4f56f4c-le64.cache-6
7efc44079000-7efc4407b000 r--s 00000000 08:02 11285387                   /var/cache/fontconfig/e8d703157d3641d20c7e900be2e8d091-le64.cache-6
7efc4407b000-7efc44080000 r--s 00000000 08:02 11285386                   /var/cache/fontconfig/b25010134a2e462c779c1c1d5ccbff7b-le64.cache-6
7efc44080000-7efc44082000 r--s 00000000 08:02 11285385                   /var/cache/fontconfig/6a6dfed4a7d1e4367ef225093de82110-le64.cache-6
7efc44082000-7efc4408f000 r--s 00000000 08:02 11285384                   /var/cache/fontconfig/089dead882dea3570ffc31a9898cfb69-le64.cache-6
7efc4408f000-7efc44090000 r--s 00000000 08:02 11285383                   /var/cache/fontconfig/30829fa25452a46451e813d634d7f916-le64.cache-6
7efc44090000-7efc44093000 r--s 00000000 08:02 11272292                   /var/cache/fontconfig/75114ca45c98e8a441da0ff356701271-le64.cache-6
7efc44093000-7efc4409e000 r--s 00000000 08:02 11272277                   /var/cache/fontconfig/83bf95040141907cd45bb53cf7c1c148-le64.cache-6
7efc4409e000-7efc4409f000 ---p 00000000 00:00 0 
7efc4409f000-7efc4489f000 rw-p 00000000 00:00 0 
7efc4489f000-7efc448c9000 r--p 00000000 08:02 5767405                    /usr/share/glib-2.0/schemas/gschemas.compiled
7efc448c9000-7efc448cd000 r-xp 00000000 08:02 8228                       /usr/lib/x86_64-linux-gnu/libcanberra-gtk3.so.0.1.9
7efc448cd000-7efc44acc000 ---p 00004000 08:02 8228                       /usr/lib/x86_64-linux-gnu/libcanberra-gtk3.so.0.1.9
7efc44acc000-7efc44acd000 r--p 00003000 08:02 8228                       /usr/lib/x86_64-linux-gnu/libcanberra-gtk3.so.0.1.9
7efc44acd000-7efc44ace000 rw-p 00004000 08:02 8228                       /usr/lib/x86_64-linux-gnu/libcanberra-gtk3.so.0.1.9
7efc44ace000-7efc44ad3000 r-xp 00000000 08:02 15071                      /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libcanberra-gtk3-module.so
7efc44ad3000-7efc44cd2000 ---p 00005000 08:02 15071                      /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libcanberra-gtk3-module.so
7efc44cd2000-7efc44cd3000 r--p 00004000 08:02 15071                      /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libcanberra-gtk3-module.so
7efc44cd3000-7efc44cd4000 rw-p 00005000 08:02 15071                      /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libcanberra-gtk3-module.so
7efc44cd4000-7efc44cdc000 r-xp 00000000 08:02 8461                       /usr/lib/x86_64-linux-gnu/libgailutil-3.so.0.0.0
7efc44cdc000-7efc44edb000 ---p 00008000 08:02 8461                       /usr/lib/x86_64-linux-gnu/libgailutil-3.so.0.0.0
7efc44edb000-7efc44edc000 r--p 00007000 08:02 8461                       /usr/lib/x86_64-linux-gnu/libgailutil-3.so.0.0.0
7efc44edc000-7efc44edd000 rw-p 00008000 08:02 8461                       /usr/lib/x86_64-linux-gnu/libgailutil-3.so.0.0.0
7efc44edd000-7efc44f39000 r-xp 00000000 08:02 9322                       /usr/lib/x86_64-linux-gnu/libzeitgeist-2.0.so.0.0.0
7efc44f39000-7efc45138000 ---p 0005c000 08:02 9322                       /usr/lib/x86_64-linux-gnu/libzeitgeist-2.0.so.0.0.0
7efc45138000-7efc4513b000 r--p 0005b000 08:02 9322                       /usr/lib/x86_64-linux-gnu/libzeitgeist-2.0.so.0.0.0
7efc4513b000-7efc4513c000 rw-p 0005e000 08:02 9322                       /usr/lib/x86_64-linux-gnu/libzeitgeist-2.0.so.0.0.0
7efc4513c000-7efc451a3000 r-xp 00000000 08:02 931                        /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.0.1
7efc451a3000-7efc453a3000 ---p 00067000 08:02 931                        /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.0.1
7efc453a3000-7efc453a6000 r--p 00067000 08:02 931                        /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.0.1
7efc453a6000-7efc453a7000 rw-p 0006a000 08:02 931                        /usr/lib/x86_64-linux-gnu/libpantheon-files-core.so.0.1
7efc453a7000-7efc453e5000 r-xp 00000000 08:02 929                        /usr/lib/x86_64-linux-gnu/libpantheon-files-widgets.so.0.1
7efc453e5000-7efc455e5000 ---p 0003e000 08:02 929                        /usr/lib/x86_64-linux-gnu/libpantheon-files-widgets.so.0.1
7efc455e5000-7efc455e7000 r--p 0003e000 08:02 929                        /usr/lib/x86_64-linux-gnu/libpantheon-files-widgets.so.0.1
7efc455e7000-7efc455e8000 rw-p 00040000 08:02 929                        /usr/lib/x86_64-linux-gnu/libpantheon-files-widgets.so.0.1
7efc455e8000-7efc455f0000 r-xp 00000000 08:02 13609                      /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libpantheon-filechooser-module.so
7efc455f0000-7efc457ef000 ---p 00008000 08:02 13609                      /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libpantheon-filechooser-module.so
7efc457ef000-7efc457f0000 r--p 00007000 08:02 13609                      /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libpantheon-filechooser-module.so
7efc457f0000-7efc457f1000 rw-p 00008000 08:02 13609                      /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libpantheon-filechooser-module.so
7efc457f1000-7efc46c43000 r--p 00000000 08:02 882                        /usr/lib/locale/locale-archive
7efc46c43000-7efc46c4e000 r-xp 00000000 08:02 14848                      /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
7efc46c4e000-7efc46e4e000 ---p 0000b000 08:02 14848                      /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so[1]    10797 abort (core dumped)  birdie
```

**Comment by nathandyer** [comment] 2017-07-03 15:56
Hey, thanks for the stacktrace! I'm going to close this issue because it's a duplicate of #181 and I want to keep everything on one issue so it's easier to track. Thank you for your report!

**Closed by nathandyer** 2017-07-03 15:56 UTC
